### ISSUE TITLE
Add ability to ignore sub-paths

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [weekitmo/flutter-assets-gen#10]
Please add the ability to ignore some paths inside the `assets_path`. For example, I might not want to generate asset paths for `fonts` inside my `assets` folder, but `fonts` should be put inside `assets` because it belongs there.

You can take example from this IntelliJ plugin:
https://plugins.jetbrains.com/plugin/15427-flutterassetsgenerator

**Comment by weekitmo** [comment]
maybe u can do this

```yaml
flutter_assets:
  assets_path: 
    - assets/images/
    - assets/msic/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
  classname: R
```

Is this the result you wanted?

**Comment by devshubhdroid** [comment]
> maybe u can do this
> 
> ```yaml
> flutter_assets:
>   assets_path: 
>     - assets/images/
>     - assets/msic/
>   output_path: lib/constants/
>   filename: assets.dart
>   field_prefix:
>   classname: R
> ```
> 
> Is this the result you wanted?

Probably kind of reverse of it, out of a ton of folders, I might want to just ignore a few. For example:

```yaml
flutter_assets:
  assets_path: 
    # Includes all its subfolders
    - assets/
  ignore_path:
    - assets/font
    - assets/splash_images
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
  classname: R
```
