### ISSUE TITLE
Remove Comments

### ISSUE THREAD

**Issue by tahadarwesh1** [weekitmo/flutter-assets-gen#12]
Is there any way to not generate the comments?

/// Assets for imagesAbout
/// assets/images/about.png

**Comment by weekitmo** [comment]
update v0.1.6

```yaml
  flutter_assets:
    assets_path: assets/
    output_path: lib/constants/
    filename: assets.dart
    field_prefix: resource
    ignore_comments: true
  ```
