### ISSUE TITLE
新需求：是否可以优化生成文件中资源名称的长度

### ISSUE THREAD

**Issue by tourdt** [weekitmo/flutter-assets-gen#2]
比如：目前生成的资源名称包含了：assertsImagesIcTabGoods = 'assets/images/ic_tab_goods.png';
是否可以把名称前面的asserts去掉，感觉有点冗余，谢谢

**Comment by weekitmo** [comment]
> 比如：目前生成的资源名称包含了：assertsImagesIcTabGoods = 'assets/images/ic_tab_goods.png'; 是否可以把名称前面的asserts去掉，感觉有点冗余，谢谢

可以，后续增加个配置来开启是否去掉吧

**Comment by weekitmo** [comment]
```yaml
  flutter_assets:
    assets_path: assets/
    output_path: lib/constants/
    filename: assets.dart
    field_prefix:
  ```
更新0.1.1
