### ISSUE TITLE
dynamic class names

### ISSUE THREAD

**Issue by codersangam** [weekitmo/flutter-assets-gen#5]
```
flutter_assets:
  assets_path: assets/icons/social/
  output_path: lib/core/constants/my_assets/icons/
  filename: social_icons.dart
  field_prefix:
```
  
By default ClassName is Assets

Expected ClassName: SocialIcons
classname can be filename.
